### ISSUE TITLE
openssl not (necessarily) available on self-hosted github actions runners

### ISSUE THREAD

**Issue by wereHamster** [nicknovitski/nix-develop#16]
Can't use this action because my self-hosted github runners only provide nix and not really anything else, and this shell script requires openssl (line 29).

Does bash not have anything builtin that we could use to generate the delimiter?

**Comment by nicknovitski** [comment]
I'm not sure.  Do your runners have the flake features enabled?  Could they run `nix run github:nicknovitski/nix-develop`, or use this project as a flake input, like the bottom of the readme says?

**Comment by nicknovitski** [comment]
This may or may not help you, but I re-arranged the README to more prominently explain how I currently think people in your position can utilize this project.  You aren't the only person with stripped-down runners; I added this feature after some other people pointed out the limitation in #8 .

**Comment by wereHamster** [comment]
Thanks, this works great!
