### ISSUE TITLE
Enter Nix Shell Step does not reflect failure status back to github

### ISSUE THREAD

**Issue by medoror-mo** [nicknovitski/nix-develop#22]
Problem Description: Subsequent pipeline steps are failing due to misconfigured attributes in my Nix configuration within the Nix flake. Ideally, I would prefer the pipeline to fail immediately at the Enter Nix Step when any errors occur to prevent unnecessary downstream failures.

Proposed Solution: Modify the Enter Nix Step to exit immediately upon encountering an error in the Nix configuration, ensuring other pipeline steps aren’t triggered when prerequisites are unmet.

![image](https://github.com/user-attachments/assets/545e9dd8-383f-450f-a071-83a71da948d9)

**Comment by nicknovitski** [comment]
I've just released v1.2.1 with a fix for this. Thank you so much for reporting it.
