### ISSUE TITLE
[Feature Request]: Working directory argument support

### ISSUE THREAD

**Issue by pedorich-n** [nicknovitski/nix-develop#7]
It would be nice if the action had a way of specifying a working directory where to look for the `flake.nix` file in case it's not in the repository's root. 
Example use case: `flake.nix` file defined in `dev` folder containing only "development" dependencies, like in [srid/haskell-flake](https://github.com/srid/haskell-flake/blob/b0491e2/dev/flake.nix#L38-L41).

**Comment by nicknovitski** [comment]
It supports arbitrary arguments, which can include any [flake reference](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake#examples) you like.  In the case you describe:
```
- use: nicknovitski/nix-develop@v1
  with:
    arguments: ./dev
```

Or if you wanted to use that repository directly, it would be `arguments: "github:srid/haskell-flake?dir=dev"`
