### ISSUE TITLE
Avoid relying on external dependencies

### ISSUE THREAD

**Issue by xgroleau** [nicknovitski/nix-develop#8]
We are using a self-hosted github runner on nixos so the environment is very minimal. When trying to use the action, it fails since openssl doesn't exist in the environment. It's used [here](https://github.com/nicknovitski/nix-develop/blob/a2060d116a50b36dfab02280af558e73ab52427d/nix-develop-gha.sh#L29), grep also seems to be used.

`nix run` could be used instead of assuming that openssl or other dependencies are installed.

**Comment by xgroleau** [comment]
I think the simplest would be to use the default nixpkgs when running `nix run nixpkgs#$APP` which uses the latest unstable commit or to lock it to a specific commit. Whichever is probably fine honestly.

**Comment by msanft** [comment]
Same use-case here. I'd find that super useful. You could default to a stable revision, and take an exact hash as an input, if required.

**Comment by nicknovitski** [comment]
resolved by #8 :)
